### ISSUE TITLE
Declarative Def/binding dialect

### ISSUE THREAD

**Issue by dginev** [dginev/latexml-oxide#93]
Hi @brucemiller and @tkw1536 ,

We have been discussing that *some* declarative variant of the DefMacro, DefPrimitive, DefConstructor, DefEnvironment, ... machinery could have been / could become a more welcoming technique than the code-based definitions.

What we haven't come up with is a proposal for a concrete syntax. Knowing what we know now, implementing this in Rust shouldn't be too hard. And we can make them work both at compile-time (if in the main project space) or at runtime (if contributed by an author, next to their .tex source).

To start off the discussion, here is a proposal for porting a more complicated constructor into a TOML variant. I chose a random example that is both illustrative and small, [\ams@url](https://github.com/brucemiller/LaTeXML/blob/2bfdaf26ab73aea95e210f044762dd4891855b47/lib/LaTeXML/Package/ams_support.sty.ltxml#L292-L294). And then added a handful more. Perl binding:
```perl
RequirePackage('amstex') if LookupValue('2.09_COMPATIBILITY');

DefPrimitiveI('\TINY', undef, '', font => { size => 3 });

DefMacro('\shorttitle{}',   '\@add@frontmatter{ltx:toctitle}{#1}');

DefConstructor('\@ams@url {}',
  "<ltx:ref href='#href'>#1</ltx:ref>",
  properties => sub { (href => CleanURL(ToString($_[1]))); });
```

and a first draft of some YAML:
```yaml
require:
  package: amstex
  condition: LookupValue('2.09_COMPATIBILITY')

define:
- \TINY:
    font: 
      size: 3

- \shorttitle{}:
    tokens: \@add@frontmatter{ltx:toctitle}{#1}

- \@ams@url {}:
    xml: <ltx:ref href='#href'>#1</ltx:ref>
    properties: 
      href: CleanURL(ToString(#1))
```

Early thoughts: 
 - it is a little easier to write a series of "objects" (i.e. hashmaps) keyed by the unique macro names. If/when the order becomes important, they can be listed in order as an array with a leading dash
 - it would be a nice "quality of life" improvement if users didn't have to state explicitly if something is a macro/constructor/primitive/environment, but that could be inferred based on the available keys, during the compile step from YAML into Rust
 - one big win of YAML over JSON is that it is a lot more permissive with which kinds of  content are valid without wrapping quotes. A downside is that we'd need to code carefully to catch oversights that are still valid YAML, but lead to misnamed macros/parameters.
 - we can still allow writing some straightforward "code" routines I think, as long as we make it clear that there is an expectation for all callers to be in scope. I.e. `LookupValue`, `CleanURL` and `ToString` must be visible in "package" and/or provided separately by the binding in question.

Discussion is most welcome - I think I'm a fan of the idea.
